[package]
name = "curve_geometry"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
embree = { path = "../../" }
support = { path = "../support" }
cgmath = "0.17.0"

