name: CI
on: [push]
jobs:
    build_linux:
        env:
            EMBREE_VERSION: 3.12.1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: wget https://github.com/embree/embree/releases/download/v${EMBREE_VERSION}/embree-${EMBREE_VERSION}.x86_64.linux.tar.gz
            - run: tar -xf embree-${EMBREE_VERSION}.x86_64.linux.tar.gz
            - run: source embree-${EMBREE_VERSION}.x86_64.linux/embree-vars.sh
            - run: echo "EMBREE_DIR=`pwd`/embree-${EMBREE_VERSION}.x86_64.linux/" >> $GITHUB_ENV
            - uses: actions-rs/cargo@v1
              with:
                  command: build
            - run: cargo test
            - run: cargo doc
            - run: scripts/build-examples-linux-mac.sh
    build_mac:
        env:
            EMBREE_VERSION: 3.12.1
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: wget https://github.com/embree/embree/releases/download/v${EMBREE_VERSION}/embree-${EMBREE_VERSION}.x86_64.macosx.zip
            - run: unzip embree-${EMBREE_VERSION}.x86_64.macosx.zip
            - run: source embree-${EMBREE_VERSION}.x86_64.macosx/embree-vars.sh
            - run: echo "EMBREE_DIR=`pwd`/embree-${EMBREE_VERSION}.x86_64.macosx/" >> $GITHUB_ENV
            - run: cp $EMBREE_DIR/lib/* .
            - uses: actions-rs/cargo@v1
              with:
                  command: build
            - run: cargo build
            - run: scripts/build-test-mac.sh
    build_windows:
        env:
            EMBREE_VERSION: 3.12.1
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: choco install wget
            - run: wget https://github.com/embree/embree/releases/download/v${env:EMBREE_VERSION}/embree-${env:EMBREE_VERSION}.x64.vc14.windows.zip
            - run: 7z x embree-${env:EMBREE_VERSION}.x64.vc14.windows.zip -y
            - run: scripts/build-test-windows.ps1

